### ISSUE TITLE
Unload Error

### ISSUE THREAD

**Issue by RustyMongoose** [electr0sheep/ItemVendorLocation#85] opened 2024-06-25 13:34 UTC
For about 3 weeks now, I've received the following error when trying to update the plugin through Dalamud

```
Installer Error
Failed to update plugin Item Vendor Location (Unload failed).
Please restart your game and try again. If this error occurs again, please contact the plugin author.
```

No further information in provided, and resetting has done nothing. The plugin still seems to function fine, but I am unable to update and given a notification every time I login that it is out of date.

**Comment by Nukoooo** [comment] 2024-06-27 05:57
The error is caused by not handling Chat 2 related stuff when unloading, this was an oversight from me. To update the plugin, you should disable every plugin by selecting ``Start w/o any Plugins``, after that you should be able to update the plugin, if not, deleting and reinstalling the plugin should fix the issue.

**Comment by Nukoooo** [comment] 2024-07-08 13:49
Closing as ApiX is out, you should be able to update the plugin once a release is made

**Closed by Nukoooo** 2024-07-08 13:49 UTC
