### ISSUE TITLE
[Bug] Showing incorrect co-ordinates/flags

### ISSUE THREAD

**Issue by Rueby** [electr0sheep/ItemVendorLocation#38] opened 2023-03-16 17:00 UTC
I initially thought that this is item or one vendor specific but I have noticed a bunch of vendors defaulted to coordinates like (11.5,11.6) in cities or close to it and around (21.9,21.8) for merchants & menders outside cities. I uninstalled and re-installed the plugin but the issue remained. Sometimes the flags show nothing or are off the map completely.

These are all examples....the issue seems to be with vendors and guild suppliers...but also seems to have extended to merchants & menders that sell various leveling gear etc. 

![image](https://user-images.githubusercontent.com/92205577/225693769-625d6757-9757-4e0a-aaec-0e0ed02f4025.png)
![image](https://user-images.githubusercontent.com/92205577/225694122-c257c9a2-e597-455d-96e6-d11f8ad2674b.png)
![image](https://user-images.githubusercontent.com/92205577/225694315-a421ee4a-ac32-43a8-8d26-2623decc81db.png)
![image](https://user-images.githubusercontent.com/92205577/225694914-f34bbcdc-5470-4739-8c1d-c45b5f57c066.png)
![image](https://user-images.githubusercontent.com/92205577/225695187-8027b889-e3a2-4f8f-82a4-20576e6e3572.png)
![image](https://user-images.githubusercontent.com/92205577/225695397-d262400e-fe87-4794-b748-06097be92f97.png)

So far, I've walked around in Ul'dah to the Sapphire Venue Exchanged, checked an item of each vendor's location and found that the coordinates are wrong.

**Comment by Rueby** [comment] 2023-03-16 17:05
![image](https://user-images.githubusercontent.com/92205577/225696568-9979cf21-5e82-4c53-be90-379c35607ee7.png)
![image](https://user-images.githubusercontent.com/92205577/225696633-a8570680-f6e9-4a8b-86fd-aa33edcdb4bb.png)

Idylshire example too

![image](https://user-images.githubusercontent.com/92205577/225696928-4bb632c2-450c-44e5-b83b-87094186b762.png)
![image](https://user-images.githubusercontent.com/92205577/225696996-6310a9eb-e4f2-4de0-aee4-49e7fee958e7.png)

Rhalgar's Reach - There's nothing there.

![image](https://user-images.githubusercontent.com/92205577/225697363-33cc662f-0199-4fd7-9ffd-4c3fe0845840.png)

**Comment by electr0sheep** [comment] 2023-03-16 23:59
Thanks for this feedback, I can confirm that there was an issue with all Garland Tools coordinates related to the recent addition of the internal data source. Pushing a fix now.

**Comment by Rueby** [comment] 2023-03-17 17:24
The issue still remains but I saw you closed this so I'm assuming it's fixed? I wonder if my plugin failed to update.

**Comment by electr0sheep** [comment] 2023-03-17 20:46
The PR hasn't been merged yet, but I do believe the issue is resolved.
Gonna try linking the PR to see if it will auto close the issue. If it does, I'll use that going forward.

**Comment by electr0sheep** [comment] 2023-03-17 20:46
https://github.com/goatcorp/DalamudPluginsD17/pull/1509

**Closed** 2023-03-22 19:38 UTC

**Comment by Rueby** [comment] 2023-03-23 06:56
It got fixed, I checked the garland tools data and it seems to be working fine. Will be using internal going forwards. Thanks alot!
