### ISSUE TITLE
Several bugs

### ISSUE THREAD

**Issue by shawnyve** [electr0sheep/ItemVendorLocation#2] opened 2022-01-22 23:43 UTC
I understand this is brand new and in testing so hopefully, this helps out.
I'm having several issues, perhaps all related.

1st. Nothing appears to happen on some items that have Vendor Buy prices when clicking on Vendor Location menu most of the time. See 2nd issue.

2nd. When clicking on Sort/Unsort which generally appears for me just above Vendor Location, on an item that can be bought, it does work. Okay, further testing showed some items work in the Armory clicking Vendor Location others I have to click sort/unsort to get the vendor list. What items do work using Vendor Location? Skysteel Hatchet, Softstepper's Turban, Custom Made Robe of Casting, and a few others which can be bought at the Calamity Vendor. What doesn't work? lots of other equipment that can be bought OR crafted. This could be the same in inventory/retainers as well.

3rd. Doesn't seem to work for Gemstone Vendor stuff. I'm guessing this is a different system but should prob state in the description it doesn't.

Feel free to msg me on discord for more info. I'm in the Goat discord. can dm me from there.

**Comment by electr0sheep** [comment] 2022-01-23 01:58
Thanks for taking a look. Out of curiosity, do you use the MarketBoardPlugin?

**Comment by rrbailey89** [comment] 2022-01-23 22:12
I also experience issue 2. Most items that I search for vendor location in my inventory nothing happens until I press the sort button.

**Comment by electr0sheep** [comment] 2022-01-24 22:05
In my own testing, I have seen this as well. There is an issue with a certain library that causes it. If you try disabling other plugins that modify the inventory context menu, then reload this plugin, the issue should resolve. Specifically for me, the MarketBoard plugin was causing the issue (not through fault of the developer). I was also able to reproduce this same bug using the PriceCheck plugin.

**Comment by thisischrys** [comment] 2022-02-19 13:19
Any news on this?
Marketboard and this plugin really shine when used together (Find it cheapest at an NPC, else cheapest on marketboard).
Right now I'm disabling one or the other when I need stuff and it's starting to get tiresome.

**Comment by electr0sheep** [comment] 2022-02-20 00:57
I think there is a fix in the works that will allow plugins to modify context menus without resulting in things like this. As soon as that gets released (and somebody else figures out how to use it), I will update the plugin.

**Comment by thakyZ** [comment] 2022-02-24 18:16
Yea, the second one is because of what @thisischrys mentioned. I have tested it too, and I can confirm that it is because of the market board plugin. I was actually coming here to report it.

**Comment by electr0sheep** [comment] 2022-04-07 23:34
I'm going to close this out, since I think the only thing outstanding is the context menu issue, which I've made a separate issue for.

**Closed by electr0sheep** 2022-04-07 23:34 UTC
Labels: bug
